fix: Update based on review comment
Signed-off-by: Debarati Basu-Nag <dbasunag@redhat.com>

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -41,14 +41,6 @@ repos:
       - id: ruff
       - id: ruff-format
 
-  # https://github.com/renovatebot/pre-commit-hooks/issues/2621
-  # This hook goes over the 250MiB limit that pre-commit.ci imposes
-  # Disable unless a solution is found.
-  # - repo: https://github.com/renovatebot/pre-commit-hooks
-  #   rev: 39.45.0
-  #   hooks:
-  #     - id: renovate-config-validator
-
   - repo: https://github.com/gitleaks/gitleaks
     rev: v8.30.0
     hooks:
@@ -64,13 +56,15 @@ repos:
 
   - repo: local
     hooks:
-        - id: check-signoff
-          name: Check Signed-off-by
-          stages: [commit-msg]
-          language: system
-          entry: >
-            bash -c 'grep -q "^Signed-off-by:" "$1" ||
-            { echo "ERROR: Commit not signed. Use git commit -s"; exit 1; }' --
+      - id: check-signoff
+        name: Check Signed-off-by
+        stages: [commit-msg]
+        language: system
+        entry: >
+          bash -c 'grep -q "^Signed-off-by: .* <.*@.*>" "$1" ||
+          { echo "ERROR: Commit message must include a valid Signed-off-by trailer.";
+          echo "  Use: git commit -s";
+          echo "  Or add manually: Signed-off-by: Your Name <your@email.com>"; exit 1; }' --
 
   - repo: https://github.com/espressif/conventional-precommit-linter
     rev: v1.11.0
